# Generated by Django 4.2.4 on 2023-08-05 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('perfil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('niveles', models.CharField(choices=[('basico', 'Básico'), ('medio', 'Medio'), ('avanzado', 'Avanzado')], default='basico', max_length=8)),
                ('curriculum_vitae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.curriculumvitae')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('experiencias', models.CharField(choices=[('principiante', 'Principiante'), ('medio', 'Medio'), ('habil', 'Hábil'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='principiante', max_length=12)),
                ('curriculum_vitae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.curriculumvitae')),
            ],
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=250)),
                ('grado', models.CharField(max_length=100)),
                ('desde', models.CharField(max_length=7)),
                ('hasta', models.CharField(max_length=7)),
                ('descripcion', models.TextField()),
                ('curriculum_vitae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.curriculumvitae')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=250)),
                ('empresa', models.CharField(max_length=250)),
                ('desde', models.CharField(max_length=7)),
                ('hasta', models.CharField(max_length=7)),
                ('descripcion', models.TextField()),
                ('curriculum_vitae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.curriculumvitae')),
            ],
        ),
    ]
